# motion/iface.py
from typing import Protocol

class MotionInterface(Protocol):
    def home(self, unit_id: str | None = None) -> None: ...
    def step(self, unit_id: str | None = None) -> None: ...
    def reset(self, unit_id: str | None = None) -> None: ...
    def state(self, unit_id: str) -> dict[str, str]: ...
