#!/usr/bin/env bash
set -euo pipefail

APP_DIR="/opt/GaseraMux"
OUT_FILE="$APP_DIR/version_info.sh"

cd "$APP_DIR"

# Ensure this is a git repo
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "❌ Not a git repository: $APP_DIR"
  exit 1
fi

HASH_FULL=$(git rev-parse HEAD)
HASH_SHORT=$(git rev-parse --short HEAD)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
DATE=$(git log -1 --format=%cd --date=short)
DESCRIBE=$(git describe --tags --always --dirty)
MESSAGE=$(git log -1 --pretty=%s | tr -d '\n')
BUILD_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "—")

cat >"$OUT_FILE" <<EOF
# Auto-generated by gen_version.sh — do not edit manually
BUILD_HASH="$HASH_FULL"
BUILD_SHORT="$HASH_SHORT"
BUILD_BRANCH="$BRANCH"
BUILD_DATE="$DATE"
BUILD_DESCRIBE="$DESCRIBE"
BUILD_MESSAGE="$MESSAGE"
BUILD_TAG="$BUILD_TAG"
EOF

chmod 644 "$OUT_FILE"
echo "✅ Version info written to $OUT_FILE"
echo "   → $HASH_SHORT ($DATE) $MESSAGE"
